[tox]
# Running tests against min/max only to speed up local iterations (all versions tested in GH actions)
envlist = py{310,314}, coverage, style

[testenv]
setenv = COVERAGE_FILE={toxworkdir}/.coverage.{envname}
usedevelop = True
deps = -rtests/requirements.txt
commands = pytest {posargs:-vv --cov=src --cov-report=xml --doctest-modules src tests}

[testenv:coverage]
setenv = COVERAGE_FILE={toxworkdir}/.coverage
skip_install = True
deps = coverage
commands = coverage combine
           coverage report -m
           coverage xml
           coverage html

[testenv:doctest]
usedevelop = True
deps = -rtests/requirements.txt
commands = pytest --doctest-modules {posargs:}

[testenv:style]
skip_install = True
deps = ruff
commands = ruff check
           ruff format --diff
           python "{toxinidir}/tests/extra-validations"

[testenv:reformat]
skip_install = True
deps = ruff
commands = ruff check --fix
           ruff format

# Type checkers: see docs/typecheckers/index.md
[testenv:basedpyright]
usedevelop = True
deps = basedpyright
       -rtests/requirements.txt
commands = basedpyright {posargs}

[testenv:mypy]
usedevelop = True
deps = mypy
       -rtests/requirements.txt
commands = mypy {posargs}

[testenv:pyrefly]
usedevelop = True
deps = pyrefly
       -rtests/requirements.txt
commands = pyrefly check {posargs}

[testenv:pyright]
usedevelop = True
deps = pyright
       -rtests/requirements.txt
commands = pyright {posargs}

[testenv:pytype]
basepython = python3.10
usedevelop = True
deps = pytype
       -rtests/requirements.txt
commands = pytype --keep-going {posargs}

[testenv:ty]
usedevelop = True
deps = ty
       -rtests/requirements.txt
commands = ty check {posargs}

[testenv:zuban]
usedevelop = True
deps = zuban
       -rtests/requirements.txt
commands = zuban check {posargs}


[coverage:run]
concurrency =
    thread
patch = subprocess
[coverage:xml]
output = .tox/test-reports/coverage.xml
[coverage:html]
directory = .tox/test-reports/htmlcov

[pytest]
cache_dir = .tox/pytest_cache
